services:
  web:
    image: nginx:latest
    volumes:
    # data shared
      - type: bind
        source: ./html
        target: /usr/share/nginx/html
    # nginx config
      - type: bind
        source: ./nginx_config/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "9090:80"
    restart: unless-stopped
    environment:
      - NGINX_PORT=80
