version: '3'

services:
  web:
    image: nginx:latest
    volumes:
    # data shared
      - type: bind
        source: ${PWD}/html
        target: /usr/share/nginx/html
    # nginx CORS
      - type: bind
        source: ${PWD}/nginx_config/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "7080:80"
    restart: on-failure
    environment:
      - NGINX_PORT=80
